# Dockerfile.airflow
FROM apache/airflow:2.7.1

# Установка зависимостей для PySpark
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-11-jdk \
    curl \
    wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Установка PySpark
RUN pip install pyspark==3.4.1
